### PR TITLE
make the capture step overridable (allow for hangouts chat time)

### PR DESCRIPTION
**Pull request by jarrodparkes**
@ke4roh this PR will support your ability to _allow for hangout chat time_ by making the capture step an overridable method (like the rules method). I think this is a better long-term solution because it will allow other users of the script to customize the parsing based on their MBOX needs

### CODE REVIEW

**Comment by jarrodparkes** [comment]
@ke4roh let me know if this works for you. you should be able to create your own custom `capture.py` that contains the changes you were wanting in your previous PR

**Comment by ke4roh** [comment]
I'm not sure- I prefer the simplicity of a script to read and little else to fiddle with.  Maybe it should just stay on a fork?

**Comment by jarrodparkes** [comment]
@ke4roh if you want to keep yours as a folk, by all means. it's a balancing act to make this tool more general purpose, having separate drivers for capturing fields and applying rules is my poor man's solution, for now

**Comment by ke4roh** [comment]
I'm curious about the diversity of applications and the universality of certain things - like how often is it the mbox file has a timestamp in the _from header?  How often does that differ from the date in the email and by how much?  Etc., etc.  I'd rather assemble some tests to see how files from different sources are handled than charge headlong into making anything work (either by coding for it, or coding to allow the user of this API to code for it).  The tests could then serve as some guide for decisions like these, and allow additional circumstances to be accommodated as they come to light.

**Comment by jarrodparkes** [comment]
@ke4roh those are great questions. I don't have any insights — only those gained from the MBOX files that I've experimented with (exports from Gmail).

I'd love to collaborate on this 👍 Do you have a sampling of different MBOX files/sources that we could use as a starting point?

**Comment by ke4roh** [comment]
I think it would suffice to start with a few tests of our examples from Gmail (such as the one I provided on PR #17). If and when someone comes along with a problem because our coding broke something, then it will be easy enough to accommodate the variation.  We can also refer to [RFC 4155](https://tools.ietf.org/html/rfc4155) for guidance, though much of the fine detail is already encapsulated in the library that reads the file.  Tests should include email and Hangouts chat, and various non-ASCII characters.  If I had an extra hour right now, I'd write an issue for these tests and get started on it, and recommend closing this one until we have those tests, at which time we'd re-evaluate.  Alas, I'm booked solid for the coming week.  Maybe next week?

**Comment by jarrodparkes** [comment]
I work on this as I have time, so at any point you get to writing tests, I'll be happy to jump in and help. I'm not certain of any standardized way of including/writing unit tests (or otherwise) for Python work like this — so if you've already got intuition/experience there, then I can follow the lead

**Pull request closed without merging**
